FROM bitnami/mariadb:latest

ENV ALLOW_EMPTY_PASSWORD=yes
ENV MARIADB_USER=${MYSQL_USER}
ENV MARIADB_PASSWORD=${MYSQL_PASSWORD}
ENV MARIADB_DATABASE=${MYSQL_DATABASE}
ENV MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

COPY *.* /docker-entrypoint-initdb.d/
